version: "3.3"  # optional since v1.27.0
services:
  server_a:
    build: .
    ports:
      - "8080:8080"

    entrypoint:
      - ./server
      - --db
      - "postgres://postgres:password@root_db:5432/monitor"

    depends_on:
      - root_db

  server_b:
    build: .
    ports:
      - "8081:8080"

    entrypoint:
      - ./server
      - --db
      - "postgres://postgres:password@root_db:5432/monitor"

    depends_on:
      - root_db

  root_db:
    image: postgres:14
    restart: always
    ports:
      - "8432:5432"

    volumes:
      - ./.db_data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: monitor

    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10

